
#Products index
GET http://localhost:3000/products.json


### Products show
GET http://localhost:3000/products/5.json


## Products create

POST  http://localhost:3000/products.json
Content-Type: application/json

{"name": "AIR JORDAN 1 X OFF-WHITE, 'Euro Release'", "price": 6690, "image_url": "https://images.unsplash.com/photo-1622831617330-bc799d6236b4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80", "description": "Virgil Abloh continued to focus his design attention on the Air Jordan 1 in 2018 by dropping a massively anticipated white colorway. The Air Jordan 1 x Off-White “White” was even harder to come by than the initial “Chicago” colorway that came out in 2017. The white version released exclusively at select retailers in Europe, and instantly became one of the most sought after sneaker releases of the year."
}


###
POST  http://localhost:3000/products.json
Content-Type: application/json

{"image_url": "https://image.goat.com/transform/v1/attachments/product_template_additional_pictures/images/054/790/005/original/697107_01.jpg.jpeg?action=crop&width=950"
}

### Products update
PATCH http://localhost:3000/products/4.json
Content-Type: application/json

{
  "name": "Nike Air Jordan 1 Mid Fearless; Maison Château Rouge"
}

PATCH http://localhost:3000/products/10.json
Content-Type: application/json

{
  "product_id": "0"
}



### Products delete
DELETE http://localhost:3000/products/.json


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Anna",
  "email": "anna@example.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "anna@example.com",
  "password": "password"
}

###

@jwt_anna = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTc4MzA4Mjh9.XA17vwp0em4q8xsauqXqA4JJXtx4ZzFrPXZxl1oI9sg


###
@jwt_test = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTc4MzEwNjd9.s-DHJIofJuAf7q7pC1AAaY9kAycyHsvCPXAvKZMhXBU

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}           



### Orders create 
POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTc4MzA4Mjh9.XA17vwp0em4q8xsauqXqA4JJXtx4ZzFrPXZxl1oI9sg
Content-Type: application/json

{
  "product_id": "2", 
  "quantity": "2"
}


### ORDERS SHOW
GET http://localhost:3000/orders/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTc4MjM5NTF9.0f-WNB4jPxmpYFF_D9ua16X5CqOqNloGt3qib-KnUpA


### ORDERS INDEX
GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTc4MjIxMjJ9.-AiAKTq8dMyt6GV8Ff4SBrD5I9BG67fUJEQVj7fk028

GET  http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTc3MzU3MTZ9.gvm7AJPI9uF4HXTrWH-Fj-y7JNncRNN63J_qKO0TAuU





#Products index
GET http://localhost:3000/products.json?category=