
#Products index
GET http://localhost:3000/products.json


### Products show

GET http://localhost:3000/products/4.json


### Products create

POST  http://localhost:3000/products.json
Content-Type: application/json
#there must be an extra-space
{
  "name": "AIR JORDAN 1 X OFF-WHITE, 'Euro Release'", 
  "price": 6690,
  "image_url": "https://images.unsplash.com/photo-1622831617330-bc799d6236b4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
  "description": ""
  
}


